baseURL = "https://www.juniordev.sg/"
languageCode = "en-us"
title = "JuniorDev.SG"
theme = "minimal"
googleAnalytics = ""
publishDir = "docs"

[params]
    author = "JunirDevSG"
    description = "Official website for JuniorDev.SG"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "images/JDGreyCircle_small.png"
    copyright = "Lovingly build by developers in Singapore"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "About Us"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://www.meetup.com/Junior-Developers-Singapore/"
    name = "meetup"
    weight = 1

[[menu.icon]]
    url = "https://github.com/juniordevsingapore/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/juniordevsg/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://launchpass.com/kopijs"
    name = "slack"
    weight = 4